name: Auto PR on Push

on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - "docs/**"
      - "chore/**"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto PR for branch ${{ github.ref_name }}"
          title: "Auto PR: ${{ github.ref_name }}"
          body: |
            This pull request was created automatically after a push to `${{ github.ref_name }}`.
            Please review and merge if appropriate.
          base: main
          branch: ${{ github.ref_name }}
          delete-branch: false
